[browser]
home_page = "http://127.0.0.1:8089/index.html"
search_page = ""
user_agent = "desktop"
persist_site_data = true
restore_tabs = false
max_tabs = 1
page_zoom = 1.0

[display]
scale = 1.0
software_render = false
use_gles = true
max_fps = 60

[input]
cursor_mode = "scroll"
edge_scroll = false
haptics = true

[game_mode]
input_map = "pad"
